# editor theme, by default it's the purple one
theme = "everforest_dark"

[editor]
scrolloff = 999
line-number = "relative"  
bufferline = "multiple" # shows bufferline when more than one buffer   

# changes the cursor shape depending on the mode you're in. 
[editor.cursor-shape] 
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

# for indent guides
[editor.indent-guides]
render = true
skip-levels = 1
#character = ""  # Some characters that work well: "▏", "┆", "┊", "⸽"


# some keymaps
# NORMAL MODE
[keys.normal]
"{" = "goto_next_paragraph"
"}" = "goto_prev_paragraph"

# SELECT MODE
[keys.select]
"{" = "goto_next_paragraph"
"}" = "goto_prev_paragraph"

# INSERT MODE
[keys.insert]
"tab" = "insert_tab"
#"C-<left>" = "move_prev_word_start"
#"C-<right>" = "move_next_word_start"

