# LSP configuration file

# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)


# append language server to existed languages
[[language]]
name = "c"
language-servers = [ "scls", "clangd" ]

[[language]]
name = "java"
language-servers = [ "scls", "jdtls"]
# add java and python...

# --> introduce a new language to enable completion on any doc by forcing set language with :set-language stub

#[[language]]
#name = "stub"
#scope = "text.stub"
#file-types = []
#shebangs = []
#roots = []
#auto-format = false
#language-servers = [ "scls" ]  
